### ISSUE TITLE
fails to build due to warning

### ISSUE THREAD

**Issue by joehealy** [meteogrid/bindings-proj4#1]
```
  /home/joe/haskell/bindings-proj4/OSGeo/Proj4.hs:111:1: warning: [-Wredundant-constraints]
        • Redundant constraints: (Real a, Fractional b)
        • In the type signature for:
               convertDouble :: (Real a, Fractional b) => a -> b
   
```

It is possible to build (stack lts-7.19) by removing the -Werror flag in the cabal file, but I suspect a better fix is trivial.

**Comment by joehealy** [comment]
Interestingly, this is not an issue on lts-8.4 (ghc 8.0.2)

**Comment by albertov** [comment]
Hi,

I've pulled the fix from your repo since forcing -Werror in the cabal file is just asking for trouble as soon as a new version of GHC is released. 

However, after reading the offending code I feel utterly ashamed so I'm about to test a better fix and commit it.

Thanks!

**Comment by joehealy** [comment]
Thanks very much.
